### ISSUE TITLE
Stopped working on Gnome 3.30

### ISSUE THREAD

**Issue by 7twin** [rliang/gnome-shell-extension-tilingnome#6]
First of all thanks for this extension!

But sadly once the update went through to Gnome 3.30 the extension installs and then just has an "undefined" error message next to it, not working at all.

GNOME version: 3.30

**Comment by aral** [comment]
Just fixed it in #7. It should start working for you once that pull request is merged (or update your extension from my gnome-shell-3.30 branch if you don’t want to wait) :)

**Comment by 7twin** [comment]
@aral amazing work, thanks! switched to awesomewm by now, but I am sure I'll use it on my next gnome install.
